apiVersion: batch/v1
kind: Job
metadata:
  name: sjg-lfp-230404-3-o4
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: container
        image: surygeng/local_field_potential:v0.1
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "4"
            memory: "64Gi"
            ephemeral-storage: "64Gi"
          limits:
            cpu: "4"
            memory: "64Gi"
            ephemeral-storage: "64Gi"
            nvidia.com/gpu: 0

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
          - >-
            python run_lfp.py s3://braingeneers/ephys/2024-03-29-e-interneurons_44/original/data/Trace_20240329_16_00_48_interneurons_44_23196.raw.h5 300 360        
        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"

          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph external
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph external

        volumeMounts:

          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}
