apiVersion: batch/v1
kind: Job
metadata:
  name: sjg-simplified-test-3b-1
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: container
          image: surygeng/ephys_pipeline:v0.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "12"
              memory: "32Gi"
              ephemeral-storage: "400Gi"
            limits:
              cpu: "12"
              memory: "32Gi"
              ephemeral-storage: "400Gi"
              nvidia.com/gpu: 1
          command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
          args:
            - >-
              ./run.sh s3://braingeneers/ephys/2024-08-19-e-3brain-test/shared/Dorsal_3DAccura_00_brw.nwb
          env:
            - name: "PYTHONUNBUFFERED"
              value: "true"
            - name: "ENDPOINT_URL"
              value: "https://s3.braingeneers.gi.ucsc.edu"
            - name: "S3_ENDPOINT"
              value: "https://s3.braingeneers.gi.ucsc.edu"
          volumeMounts:
            - name: "prp-s3-credentials"
              mountPath: "/root/.aws/credentials"
              subPath: "credentials"
            - name: ephemeral
              mountPath: "/root"
      tolerations:
        - key: "msu-cache"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/5g"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/csusb"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/gitlab-issue"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/gpu-untested"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/prism-center"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/sdsc-llm"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/slow-network"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/suncave"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/testing"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/u55c"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-01.nrp.mghpcc.org
                      - gpu-02.nrp.mghpcc.org
                      - gpu-03.nrp.mghpcc.org
                      - gpu-04.nrp.mghpcc.org
                      - gpu-05.nrp.mghpcc.org
                      - gpu-06.nrp.mghpcc.org
                      - gpu-07.nrp.mghpcc.org
                      - gpu-08.nrp.mghpcc.org
                      - gpu-09.nrp.mghpcc.org
                      - gpu-10.nrp.mghpcc.org
                      - gpu-11.nrp.mghpcc.org
                      - gpu-12.nrp.mghpcc.org
                      - gpu-13.nrp.mghpcc.org
                      - gpu-14.nrp.mghpcc.org
                      - gpu-15.nrp.mghpcc.org
                      - gpu-16.nrp.mghpcc.org
                      - gpu-17.nrp.mghpcc.org
                      - gpu-18.nrp.mghpcc.org
                      - hcc-nrp-shor-c5809.unl.edu
                      - hcc-nrp-shor-c5813.unl.edu
                      - hcc-nrp-shor-c5817.unl.edu
                      - hcc-nrp-shor-c5821.unl.edu
                      - hcc-nrp-shor-c5825.unl.edu
                      - hcc-nrp-shor-c5905.unl.edu
                      - hcc-nrp-shor-c5909.unl.edu
                      - hcc-nrp-shor-c5913.unl.edu
                      - hcc-nrp-shor-c5917.unl.edu
                      - hcc-nrp-shor-c5921.unl.edu
                      - hcc-nrp-shor-c5925.unl.edu
                      - hcc-nrp-shor-c6009.unl.edu
                      - hcc-nrp-shor-c6013.unl.edu
                      - hcc-nrp-shor-c6017.unl.edu
                      - hcc-nrp-shor-c6021.unl.edu
                      - hcc-nrp-shor-c6025.unl.edu
      restartPolicy: Never
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}