apiVersion: batch/v1
kind: Job
metadata:
  name: sjg-alg-connectivity-1
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: container
        image: surygeng/connectivity:v0.1
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "8Gi"
          limits:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "8Gi"
            nvidia.com/gpu: 0

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
          - >-
            python run_conn.py s3://braingeneers/ephys/2024-08-02-e-atenea/derived/kilosort2/Trace_20240802_14_19_02_ventraldisso_day18_23133_acqm.zip s3://braingeneers/services/mqtt_job_listener/params/connectivity/params_default.json
        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"

          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph external
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph external

        volumeMounts:
          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}

