apiVersion: batch/v1
kind: Job
metadata:
  name: edp-viz-test-2
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: container
        image: surygeng/visualization:v0.1
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "8Gi"
          limits:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "8Gi"
            nvidia.com/gpu: 0

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
          - >-
            python viz.py s3://braingeneers/integrated/2023-09-16-efi-mouse-5plex-official/ephys/derived/pipeline/19894/2023-09-23-T070000-chip19894_acqm.zip
        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"

          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph internal
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph internal

        volumeMounts:

          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}
