apiVersion: batch/v1
kind: Job
metadata:
  name: sjg-viz-11
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - args:
        - python viz.py s3://braingeneers/ephys/2024-09-06-e-umass-Pak_ASD_d28_d49/derived/kilosort2/A4927_14248_Tri_d49_acqm.zip
        command:
        - stdbuf
        - -i0
        - -o0
        - -e0
        - /usr/bin/time
        - -v
        - bash
        - -c
        env:
        - name: PYTHONUNBUFFERED
          value: 'true'
        - name: ENDPOINT_URL
          value: https://s3.braingeneers.gi.ucsc.edu
        - name: S3_ENDPOINT
          value: s3.braingeneers.gi.ucsc.edu
        image: surygeng/visualization:v0.1
        imagePullPolicy: Always
        name: container
        resources:
          limits:
            cpu: '2'
            ephemeral-storage: 8Gi
            memory: 16Gi
            nvidia.com/gpu: 0
          requests:
            cpu: '2'
            ephemeral-storage: 8Gi
            memory: 16Gi
        volumeMounts:
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
      restartPolicy: Never
      volumes:
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials
      - emptyDir: {}
        name: ephemeral
